name: .NET

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GarageGroup NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # CodeAnalysis.SourceBuilder

    - name: Restore CodeAnalysis.SourceBuilder
      run: dotnet restore ./src/*/CodeAnalysis.SourceBuilder.csproj

    - name: Build CodeAnalysis.SourceBuilder
      run: dotnet build ./src/*/CodeAnalysis.SourceBuilder.csproj --no-restore  -c Release

    - name: Pack CodeAnalysis.SourceBuilder
      run: dotnet pack ./src/*/CodeAnalysis.SourceBuilder.csproj --no-restore -o ~/nuget  -c Release

    # CodeAnalysis.Extensions

    - name: Restore CodeAnalysis.Extensions
      run: dotnet restore ./src/*/CodeAnalysis.Extensions.csproj

    - name: Build CodeAnalysis.Extensions
      run: dotnet build ./src/*/CodeAnalysis.Extensions.csproj --no-restore  -c Release

    - name: Pack CodeAnalysis.Extensions
      run: dotnet pack ./src/*/CodeAnalysis.Extensions.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ secrets.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate